---
exclusions:
  - .DS_Store
  - .ICEauthority
  - .IdeaIC20
  - .Trash/
  - .Xauthority
  - .android/
  - .bash_history
  - .bash_secrets
  - .cache/
  - .cargo/.package-cache
  - .cargo/git/
  - .cargo/registry/
  - .cinnamon/
  - .cinnamon/glass.log
  - .cinnamon/spices.cache/
  - .config/chrome-profile-
  - .config/chrome-remote-desktop/
  - .config/d-feet/
  - .config/dconf/user
  - .config/eog/
  - .config/gedit/
  - .config/google-chrome/
  - .config/gtk-2.0/
  - .config/gtk-3.0/
  - .config/libreoffice/
  - .config/monitors.xml
  - .config/pulse/
  - .config/vlc/
  - .config/yet-another-timer/
  - .cups/lpoptions
  - .dbus/session-bus/
  - .esets/
  - .face
  - .gksu.lock
  - .gnome/apps/
  - .ipython/profile_default/history.sqlite
  - .java/
  - .lesshst
  - .local/lib/python
  - .local/share/JetBrains/
  - .local/share/Trash
  - .local/share/applications/
  - .local/share/cinnamon/
  - .local/share/clipit/
  - .local/share/desktop-directories/
  - .local/share/gvfs-metadata/
  - .local/share/icc/
  - .local/share/icons/
  - .local/share/keyrings/
  - .local/share/locale/
  - .local/share/mime/
  - .local/share/radiotray/radiotray.log
  - .local/share/recently-used.xbel
  - .local/share/user-places.xbel
  - .local/share/virtualenvs/
  - .local/share/vlc/
  - .mozilla/
  - .oracle_jre_usage/
  - .parallel/
  - .pip/pip.log
  - .pki/
  - .python_history
  - .secureConnect
  - .sqlite_history
  - .ssh/
  - .vagrant.d/
  - .vim/.netrwhist
  - .viminfo
  - .vimtemp/undo/
  - .vimtemp/swap/
  - .wget-hsts
  - .xsession-errors
  - .xsession-errors.old
  - .zsh_history

plist_exclusions:
  # TODO: Add a first app exclusions here
