#!/bin/bash
# Source: https://github.com/rtomayko/dotfiles/blob/rtomayko/bin/markdown-open

f=$1
if [ -z "$f" ] || [ "$f" = "-" ] ; then
  f=/tmp/markdown-$$.txt
  cat > $f
  trap "rm -f $f" 0
elif ! [ -f "$f" ] ; then
    echo "$f does not exist"
    exit 1
fi

bn=$(basename $f | sed 's:^\(.*\)\.txt$:\1:')
html_file="$(dirname $f)/$bn.html"
cat <<EOF > "$html_file"
<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>$f</title>
  <link href="https://github.com/assets/github.css" media="screen" rel="stylesheet" type="text/css" />
  <style type="text/css">
    div#container {
      max-width:  852px;
      margin:     50px auto;
    }
  </style>
  <body>
    <div id="container" class="markdown-body">
EOF
cat "$f" | markdown >> "$html_file"
cat <<EOF >> "$html_file"
    </div>
  </body>
</html>
EOF
rslt=$?
[ $rslt != 0 ] && exit $rslt
xdg-open "$html_file" 2>/dev/null
sleep 10
unlink "$html_file"
echo
