#!/usr/bin/env python3
# Run ipython with packages
# Inspired by https://til.simonwillison.net/python/itry

import os
import sys


if len(sys.argv) >= 2 and sys.argv[1] == "--help":
    sys.stderr.write(f'{sys.argv[0]} [packages]\n')
    sys.stderr.write(f'Example: {sys.argv[0]} llm cowsay\n')
    os.exit(0)

python_version = '3.13'
cmd = ['uvx' , '--python', python_version]
for package in sys.argv[1:]:
    cmd.append('--with')
    cmd.append(package)
cmd.append('ipython')

print(' '.join(cmd))
os.execvp(cmd[0], cmd)
