#!/bin/bash
# This hook is run after every virtualenv is activated.

# Enter work directory if it exists
WORK_DIR="$HOME/workspace/`basename $VIRTUAL_ENV`"
[ -d ${WORK_DIR} ] && cd $WORK_DIR

function get_manage_script() {
    # Find manage.py script
    find -name 'manage.py' | head -1
}

function get_bind_address() {
    PORT=${1:-0.0.0.0:8080}
    expr index "$PORT" ":" > /dev/null || PORT="0.0.0.0:$PORT"
    echo $PORT
}

function r() {
    `get_manage_script` runserver `get_bind_address $1`
}

function rr() {
    `get_manage_script` runserver_plus `get_bind_address $1`
}

function s() {
    `get_manage_script` shell_plus $@
}

function m() {
    `get_manage_script` $@
}
