#!/usr/bin/env python3
"""Set the hostname on the machine.

Supports different operating systems.
"""

import os
import platform
import subprocess
import sys


def set_mac_hostname(hostname):
    human_name = hostname.title()
    subprocess.check_call(["sudo", "scutil", "--set", "ComputerName", human_name])
    subprocess.check_call(["sudo", "scutil", "--set", "HostName", hostname])
    # Used for access via $name.local
    subprocess.check_call(["sudo", "scutil", "--set", "LocalHostName", hostname])
    subprocess.check_call(
        [
            "sudo",
            "defaults",
            "write",
            "/Library/Preferences/SystemConfiguration/com.apple.smb.server",
            "NetBIOSName",
            "-string",
            hostname,
        ]
    )


def set_linux_hostname(hostname):
    subprocess.check_call(["hostnamectl", "set-hostname", hostname])


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(f"Usage: {sys.argv[0]} <hostname>")
        os.exit(1)

    hostname = sys.argv[1]
    system = platform.system()
    if system == "Darwin":
        set_mac_hostname(hostname)
    elif system == "Linux":
        set_linux_hostname(hostname)
    else:
        raise ValueError(f"Unsupported {system=}")


if __name__ == "__main__":
    main()
